<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>CodeTiburon Billboard</title>
    <meta name="description" content="CodeTiburon Billboard Demo Project">
    <meta name="author" content="CodeTiburon">

    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />

    <link rel="stylesheet" type="text/css" href="/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/css/layout.css">
    <?= $HEADER ?>
</head>

<body>

<div id="page">
    <?= $CONTENT ?>
</div>

<script type="application/javascript" src="/js/lib/jquery.js"></script>
<script type="application/javascript" src="/js/lib/jquery.form.js"></script>
<script type="application/javascript" src="/js/layout.js"></script>
<?= $FOOTER ?>
</body>
</html>